# Generated by Django 3.2 on 2021-04-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('s_fname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('m_number', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=50)),
                ('date_join', models.DateField()),
                ('c_position', models.BooleanField(default=True)),
            ],
        ),
    ]
