# Generated by Django 3.2 on 2021-05-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210513_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearclass',
            name='id',
        ),
        migrations.AlterField(
            model_name='yearclass',
            name='year',
            field=models.IntegerField(default=2021, primary_key=True, serialize=False),
        ),
    ]
