# Generated by Django 3.2 on 2021-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210513_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=50)),
                ('t_fname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('m_number', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=50)),
                ('date_hiring', models.DateField()),
                ('c_position', models.BooleanField(default=True)),
                ('sex', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=200)),
                ('fm_number', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('speciality', models.CharField(max_length=200)),
            ],
        ),
    ]
