# Generated by Django 3.2 on 2021-05-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacherdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachpaymonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.PositiveSmallIntegerField()),
                ('february', models.PositiveSmallIntegerField()),
                ('march', models.PositiveSmallIntegerField()),
                ('april', models.PositiveSmallIntegerField()),
                ('may', models.PositiveSmallIntegerField()),
                ('june', models.PositiveSmallIntegerField()),
                ('july', models.PositiveSmallIntegerField()),
                ('august', models.PositiveSmallIntegerField()),
                ('september', models.PositiveSmallIntegerField()),
                ('october', models.PositiveSmallIntegerField()),
                ('november', models.PositiveSmallIntegerField()),
                ('december', models.PositiveSmallIntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teacherdetail')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.yearclass')),
            ],
        ),
    ]
