# Generated by Django 3.2 on 2021-05-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_teachpaymonths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachpaymonths',
            name='april',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='august',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='december',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='february',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='january',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='july',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='june',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='march',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='may',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='november',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='october',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachpaymonths',
            name='september',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
