# Generated by Django 3.2 on 2021-05-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210529_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectmarks', models.PositiveSmallIntegerField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.schoolclasses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentsdetail')),
                ('subjectname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.subjects')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.yearclass')),
            ],
        ),
    ]
